// The page elements that the modules update.

export const dom = {
  librarySummary: document.getElementById("library-summary"),
  filterFrom: document.getElementById("filter-from"),
  filterTo: document.getElementById("filter-to"),
  filterQuery: document.getElementById("filter-query"),
  streetNames: document.getElementById("street-names"),
  dateFilter: document.getElementById("date-filter"),
  dateSlider: document.getElementById("date-slider"),
  dateSliderFrom: document.getElementById("date-slider-from"),
  dateSliderTo: document.getElementById("date-slider-to"),
  datePresets: document.getElementById("date-presets"),
  colorControls: document.getElementById("color-controls"),
  heatControl: document.getElementById("heat-control"),
  heatToggle: document.getElementById("heat-toggle"),
  summary: document.getElementById("summary"),
  tripBrowser: document.getElementById("trip-browser"),
  tripList: document.getElementById("trip-list"),
  noGpsTrips: document.getElementById("no-gps-trips"),
  tripDetail: document.getElementById("trip-detail"),
  mapArea: document.getElementById("map-area"),
  mapStatus: document.getElementById("map-status"),
  mapStatusText: document.getElementById("map-status-text"),
  videoPanel: document.getElementById("video-panel"),
  videoHeader: document.querySelector("#video-panel .video-header"),
  videoTitle: document.getElementById("video-title"),
  videoSource: document.getElementById("video-source"),
  videoContainer: document.getElementById("video-container"),
  videoMessage: document.getElementById("video-message"),
};
